/* DO NOT EDIT THIS FILE */
package com.hapz.assessment.model;

import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

@Entity
public class SearchCache implements Serializable {

    /**
	 * 
	 */
	private static final long serialVersionUID = -2308866818774038977L;

	@Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String query;

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
    @JoinColumn(name = "query")
    private List<SearchCacheMovie> searchResults;

    public SearchCache() {
    }

    public SearchCache(String query, List<SearchCacheMovie> searchResults) {
        this.query = query;
        this.searchResults = searchResults;
    }

    public Long getId() {
        return id;
    }

    public String getQuery() {
        return query;
    }

    public void setQuery(String query) {
        this.query = query;
    }

    public List<SearchCacheMovie> getSearchResults() {
        return searchResults;
    }

    public void setSearchResults(List<SearchCacheMovie> searchResults) {
        this.searchResults = searchResults;
    }
}
