/* DO NOT EDIT THIS FILE */
package com.hapz.assessment.model;

import java.io.Serializable;

import javax.persistence.*;

@Entity
public class SearchCacheMovie implements Serializable {

    /**
	 * 
	 */
	private static final long serialVersionUID = -2824522047777194219L;

	@Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String movieTitle;

    public SearchCacheMovie() {
    }

    public SearchCacheMovie(String movieTitle) {
        this.movieTitle = movieTitle;
    }

    public Long getId() {
        return id;
    }

    public String getMovieTitle() {
        return movieTitle;
    }

    public void setMovieTitle(String movieTitle) {
        this.movieTitle = movieTitle;
    }
}
